"""Export a trained TinyPolicy checkpoint to dependency-free C for MCU deployment.

The onboard-compute seam (docs/ONBOARD_COMPUTE.md): emits a single self-contained
``tiny_policy.c`` (weights as const arrays + a float32 forward pass, puffernet-style —
the pattern tensaur/drone proved on a Crazyflie STM32F405 at 100 Hz) plus a
``test_main.c`` harness with torch-generated test vectors baked in, so parity can be
verified on any target with just a C compiler.

Usage:
  uv run python scripts/export_c.py --from runs/<run>/ckpt_final.pt [--out DIR] [--n-test 32]

Then (host parity + timing):
  cc -O2 -o test_policy DIR/tiny_policy.c DIR/test_main.c -lm && ./test_policy

Cross-compile size check (zig makes this toolchain-free):
  zig cc -target thumb-freestanding-eabihf -mcpu=cortex_m4 -O2 -c DIR/tiny_policy.c -o m4.o && size m4.o
"""

from __future__ import annotations

import argparse
import os

import torch


def _fmt_floats(t: torch.Tensor, per_line: int = 8) -> str:
    vals = [f"{v:.9e}f" for v in t.flatten().tolist()]
    lines = [", ".join(vals[i : i + per_line]) for i in range(0, len(vals), per_line)]
    return ",\n    ".join(lines)


def export_c(ckpt_path: str, out_dir: str, n_test: int = 32, seed: int = 0) -> dict:
    d = torch.load(ckpt_path, map_location="cpu", weights_only=True)
    sd = d["model"]
    obs_dim, act_dim = int(d["obs_dim"]), int(d["act_dim"])
    act_name = dict(d.get("ppo_cfg", {})).get("activation", "tanh")
    act_expr = {"tanh": "tanhf(h)", "relu": "h > 0.0f ? h : 0.0f"}[act_name]

    # Collect actor Linear layers in order (actor.net.<i>.weight, torch layout [out, in]).
    idxs = sorted({int(k.split(".")[2]) for k in sd if k.startswith("actor.net.") and k.endswith(".weight")})
    layers = [(sd[f"actor.net.{i}.weight"], sd[f"actor.net.{i}.bias"]) for i in idxs]
    dims = [obs_dim] + [w.shape[0] for w, _ in layers]
    assert dims[-1] == act_dim, (dims, act_dim)
    n_params = sum(w.numel() + b.numel() for w, b in layers)
    max_h = max(dims)

    # Reference outputs from the exact deploy semantics: linears + activation, final clamp.
    gen = torch.Generator().manual_seed(seed)
    test_obs = torch.randn(n_test, obs_dim, generator=gen)
    with torch.no_grad():
        h = test_obs
        for j, (w, b) in enumerate(layers):
            h = h @ w.T + b
            if j < len(layers) - 1:
                h = torch.tanh(h) if act_name == "tanh" else torch.relu(h)
        test_act = h.clamp(-1.0, 1.0)

    os.makedirs(out_dir, exist_ok=True)
    parts = [
        "/* Auto-generated by scripts/export_c.py — do not edit.",
        f" * Source: {ckpt_path} (step {int(d.get('global_step', -1))}, task {d.get('task')!r})",
        f" * TinyPolicy obs{obs_dim} -> {' -> '.join(str(x) for x in dims[1:])}, {act_name} hidden, clamp[-1,1] out.",
        f" * {n_params} params, float32. */",
        "#include <math.h>",
        "",
        f"#define TP_OBS_DIM {obs_dim}",
        f"#define TP_ACT_DIM {act_dim}",
        "",
    ]
    for j, (w, b) in enumerate(layers):
        parts.append(f"static const float W{j}[{w.numel()}] = {{\n    {_fmt_floats(w)}\n}};")
        parts.append(f"static const float B{j}[{b.numel()}] = {{\n    {_fmt_floats(b)}\n}};")
    parts += [
        "",
        "/* obs[TP_OBS_DIM] -> act[TP_ACT_DIM]; ~%d MACs, two %d-float scratch buffers. */" % (
            sum(dims[i] * dims[i + 1] for i in range(len(dims) - 1)), max_h),
        "void tiny_policy_forward(const float* obs, float* act) {",
        f"    static float buf_a[{max_h}], buf_b[{max_h}];",
        "    const float* x = obs;",
        "    float* y = buf_a;",
    ]
    for j, (w, _) in enumerate(layers):
        n_in, n_out = w.shape[1], w.shape[0]
        last = j == len(layers) - 1
        parts += [
            f"    {{ /* layer {j}: {n_in} -> {n_out} */",
            f"        const float* Wp = W{j};",
            f"        for (int o = 0; o < {n_out}; o++) {{",
            f"            float h = B{j}[o];",
            f"            for (int i = 0; i < {n_in}; i++) h += Wp[o * {n_in} + i] * x[i];",
            (f"            act[o] = h < -1.0f ? -1.0f : (h > 1.0f ? 1.0f : h);" if last
             else f"            y[o] = {act_expr};"),
            "        }",
            ("" if last else f"        x = y; y = (y == buf_a) ? buf_b : buf_a;"),
            "    }",
        ]
    parts.append("}")
    with open(os.path.join(out_dir, "tiny_policy.c"), "w") as f:
        f.write("\n".join(p for p in parts if p is not None) + "\n")

    harness = [
        "/* Parity + timing harness with torch-generated vectors baked in. */",
        "#include <stdio.h>",
        "#include <math.h>",
        "#include <time.h>",
        f"#define N_TEST {n_test}",
        f"extern void tiny_policy_forward(const float* obs, float* act);",
        f"static const float TEST_OBS[N_TEST][{obs_dim}] = {{",
        *[f"    {{ {_fmt_floats(test_obs[i])} }}," for i in range(n_test)],
        "};",
        f"static const float TEST_ACT[N_TEST][{act_dim}] = {{",
        *[f"    {{ {_fmt_floats(test_act[i])} }}," for i in range(n_test)],
        "};",
        "int main(void) {",
        f"    float out[{act_dim}];",
        "    double max_err = 0.0;",
        "    for (int t = 0; t < N_TEST; t++) {",
        "        tiny_policy_forward(TEST_OBS[t], out);",
        f"        for (int a = 0; a < {act_dim}; a++) {{",
        "            double e = fabs((double)out[a] - (double)TEST_ACT[t][a]);",
        "            if (e > max_err) max_err = e;",
        "        }",
        "    }",
        "    printf(\"parity_max_abs_err %.3e\\n\", max_err);",
        "    struct timespec t0, t1;",
        "    volatile float sink = 0.0f;",
        "    clock_gettime(CLOCK_MONOTONIC, &t0);",
        "    const int iters = 200000;",
        "    for (int k = 0; k < iters; k++) {",
        "        tiny_policy_forward(TEST_OBS[k % N_TEST], out);",
        "        sink += out[0];",
        "    }",
        "    clock_gettime(CLOCK_MONOTONIC, &t1);",
        "    double ns = (t1.tv_sec - t0.tv_sec) * 1e9 + (t1.tv_nsec - t0.tv_nsec);",
        "    printf(\"host_ns_per_inference %.1f\\n\", ns / iters);",
        "    return max_err < 1e-5 ? 0 : 1;",
        "}",
    ]
    with open(os.path.join(out_dir, "test_main.c"), "w") as f:
        f.write("\n".join(harness) + "\n")

    return {"obs_dim": obs_dim, "act_dim": act_dim, "dims": dims, "n_params": n_params,
            "macs": sum(dims[i] * dims[i + 1] for i in range(len(dims) - 1)),
            "weights_bytes_f32": n_params * 4, "activation": act_name}


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="ckpt", required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--n-test", type=int, default=32)
    args = ap.parse_args()
    out = args.out or os.path.join(os.path.dirname(args.ckpt), "deploy_c")
    info = export_c(args.ckpt, out)
    print(f"wrote {out}/tiny_policy.c + test_main.c")
    for k, v in info.items():
        print(f"  {k}: {v}")
